/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author rdare
 */
public class form_detallesFacturas extends javax.swing.JFrame {

    /**
     * Creates new form form_detallesFacturas
     */
    public form_detallesFacturas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPdetallesFactura = new javax.swing.JPanel();
        TXXtotal = new javax.swing.JTextField();
        TXTnFactura = new javax.swing.JTextField();
        TXTigv = new javax.swing.JTextField();
        TXTcod_Empresa = new javax.swing.JTextField();
        TXTcodUsuario = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TBLdetallesFactura = new javax.swing.JTable(){
            public boolean isCellEditable(int rowindex, int colIndex){
                return false;
            }
        };
        TXTfecha = new javax.swing.JTextField();
        TXTsubtotal = new javax.swing.JTextField();
        TXTtipoMoneda = new javax.swing.JTextField();
        TXTtipoPago = new javax.swing.JTextField();
        TXTestado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DETALLES FACTURA");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPdetallesFactura.setBackground(new java.awt.Color(18, 22, 31));
        JPdetallesFactura.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TXXtotal.setEditable(false);
        TXXtotal.setBackground(new java.awt.Color(18, 22, 31));
        TXXtotal.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        TXXtotal.setForeground(new java.awt.Color(255, 255, 255));
        TXXtotal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TOTAL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12), new java.awt.Color(0, 255, 51))); // NOI18N
        JPdetallesFactura.add(TXXtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 160, 190, 50));

        TXTnFactura.setEditable(false);
        TXTnFactura.setBackground(new java.awt.Color(18, 22, 31));
        TXTnFactura.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        TXTnFactura.setForeground(new java.awt.Color(255, 255, 255));
        TXTnFactura.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "N°  FACTURA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        JPdetallesFactura.add(TXTnFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 190, 50));

        TXTigv.setEditable(false);
        TXTigv.setBackground(new java.awt.Color(18, 22, 31));
        TXTigv.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        TXTigv.setForeground(new java.awt.Color(255, 255, 255));
        TXTigv.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "I.G.V (18%)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        JPdetallesFactura.add(TXTigv, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 90, 190, 50));

        TXTcod_Empresa.setEditable(false);
        TXTcod_Empresa.setBackground(new java.awt.Color(18, 22, 31));
        TXTcod_Empresa.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        TXTcod_Empresa.setForeground(new java.awt.Color(255, 255, 255));
        TXTcod_Empresa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "COD_EMPRESA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        JPdetallesFactura.add(TXTcod_Empresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 190, 50));

        TXTcodUsuario.setEditable(false);
        TXTcodUsuario.setBackground(new java.awt.Color(18, 22, 31));
        TXTcodUsuario.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        TXTcodUsuario.setForeground(new java.awt.Color(255, 255, 255));
        TXTcodUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "COD_USUARIO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        JPdetallesFactura.add(TXTcodUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 190, 50));

        TBLdetallesFactura.setBackground(new java.awt.Color(18, 22, 31));
        TBLdetallesFactura.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        TBLdetallesFactura.setForeground(new java.awt.Color(255, 255, 255));
        TBLdetallesFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "COD_PRODUCTO", "DESCRIPCION", "PRECIO", "CANTIDAD", "IMPORTE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TBLdetallesFactura.setToolTipText("");
        TBLdetallesFactura.setGridColor(new java.awt.Color(21, 25, 34));
        TBLdetallesFactura.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(TBLdetallesFactura);

        JPdetallesFactura.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 880, 350));

        TXTfecha.setEditable(false);
        TXTfecha.setBackground(new java.awt.Color(18, 22, 31));
        TXTfecha.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        TXTfecha.setForeground(new java.awt.Color(255, 255, 255));
        TXTfecha.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FECHA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        JPdetallesFactura.add(TXTfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 190, 50));

        TXTsubtotal.setEditable(false);
        TXTsubtotal.setBackground(new java.awt.Color(18, 22, 31));
        TXTsubtotal.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        TXTsubtotal.setForeground(new java.awt.Color(255, 255, 255));
        TXTsubtotal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SUBTOTAL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        JPdetallesFactura.add(TXTsubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, 190, 50));

        TXTtipoMoneda.setEditable(false);
        TXTtipoMoneda.setBackground(new java.awt.Color(18, 22, 31));
        TXTtipoMoneda.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        TXTtipoMoneda.setForeground(new java.awt.Color(255, 255, 255));
        TXTtipoMoneda.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TIPO DE MONEDA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        JPdetallesFactura.add(TXTtipoMoneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 190, 50));

        TXTtipoPago.setEditable(false);
        TXTtipoPago.setBackground(new java.awt.Color(18, 22, 31));
        TXTtipoPago.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        TXTtipoPago.setForeground(new java.awt.Color(255, 255, 255));
        TXTtipoPago.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TIPO DE PAGO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        JPdetallesFactura.add(TXTtipoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 190, 50));

        TXTestado.setEditable(false);
        TXTestado.setBackground(new java.awt.Color(18, 22, 31));
        TXTestado.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        TXTestado.setForeground(new java.awt.Color(255, 255, 255));
        TXTestado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ESTADO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        JPdetallesFactura.add(TXTestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 190, 50));

        getContentPane().add(JPdetallesFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_detallesFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_detallesFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_detallesFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_detallesFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_detallesFacturas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPdetallesFactura;
    public javax.swing.JTable TBLdetallesFactura;
    public javax.swing.JTextField TXTcodUsuario;
    public javax.swing.JTextField TXTcod_Empresa;
    public javax.swing.JTextField TXTestado;
    public javax.swing.JTextField TXTfecha;
    public javax.swing.JTextField TXTigv;
    public javax.swing.JTextField TXTnFactura;
    public javax.swing.JTextField TXTsubtotal;
    public javax.swing.JTextField TXTtipoMoneda;
    public javax.swing.JTextField TXTtipoPago;
    public javax.swing.JTextField TXXtotal;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
