/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author rdare
 */
public class form_detallesBoletas extends javax.swing.JFrame {

    /**
     * Creates new form form_detallesFactura
     */
    public form_detallesBoletas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPdetallesBoletas = new javax.swing.JPanel();
        TXTestado = new javax.swing.JTextField();
        TXTnBoleta = new javax.swing.JTextField();
        TXTcod_Cliente = new javax.swing.JTextField();
        TXTcodUsuario = new javax.swing.JTextField();
        TXTtipo_pago = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TBLdetallesBoleta = new javax.swing.JTable(){
            public boolean isCellEditable(int rowindex, int colIndex){
                return false;
            }
        };
        TXTfecha = new javax.swing.JTextField();
        TXTtotal = new javax.swing.JTextField();
        TXTtipo_moneda = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JPdetallesBoletas.setBackground(new java.awt.Color(18, 22, 31));
        JPdetallesBoletas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TXTestado.setEditable(false);
        TXTestado.setBackground(new java.awt.Color(18, 22, 31));
        TXTestado.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        TXTestado.setForeground(new java.awt.Color(255, 255, 255));
        TXTestado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ESTADO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        JPdetallesBoletas.add(TXTestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 260, 50));

        TXTnBoleta.setEditable(false);
        TXTnBoleta.setBackground(new java.awt.Color(18, 22, 31));
        TXTnBoleta.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        TXTnBoleta.setForeground(new java.awt.Color(255, 255, 255));
        TXTnBoleta.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "N°  BOLETA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        JPdetallesBoletas.add(TXTnBoleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 260, 50));

        TXTcod_Cliente.setEditable(false);
        TXTcod_Cliente.setBackground(new java.awt.Color(18, 22, 31));
        TXTcod_Cliente.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        TXTcod_Cliente.setForeground(new java.awt.Color(255, 255, 255));
        TXTcod_Cliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "COD_CLIENTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        JPdetallesBoletas.add(TXTcod_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 260, 50));

        TXTcodUsuario.setEditable(false);
        TXTcodUsuario.setBackground(new java.awt.Color(18, 22, 31));
        TXTcodUsuario.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        TXTcodUsuario.setForeground(new java.awt.Color(255, 255, 255));
        TXTcodUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "COD_USUARIO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        JPdetallesBoletas.add(TXTcodUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 260, 50));

        TXTtipo_pago.setEditable(false);
        TXTtipo_pago.setBackground(new java.awt.Color(18, 22, 31));
        TXTtipo_pago.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        TXTtipo_pago.setForeground(new java.awt.Color(255, 255, 255));
        TXTtipo_pago.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TIPO_PAGO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        JPdetallesBoletas.add(TXTtipo_pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 260, 50));

        TBLdetallesBoleta.setBackground(new java.awt.Color(18, 22, 31));
        TBLdetallesBoleta.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        TBLdetallesBoleta.setForeground(new java.awt.Color(255, 255, 255));
        TBLdetallesBoleta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "COD_PRODUCTO", "DESCRIPCION", "PRECIO", "CANTIDAD", "IMPORTE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TBLdetallesBoleta.setToolTipText("");
        TBLdetallesBoleta.setGridColor(new java.awt.Color(21, 25, 34));
        TBLdetallesBoleta.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(TBLdetallesBoleta);

        JPdetallesBoletas.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 880, 350));

        TXTfecha.setEditable(false);
        TXTfecha.setBackground(new java.awt.Color(18, 22, 31));
        TXTfecha.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        TXTfecha.setForeground(new java.awt.Color(255, 255, 255));
        TXTfecha.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FECHA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        JPdetallesBoletas.add(TXTfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, 260, 50));

        TXTtotal.setEditable(false);
        TXTtotal.setBackground(new java.awt.Color(18, 22, 31));
        TXTtotal.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        TXTtotal.setForeground(new java.awt.Color(255, 255, 255));
        TXTtotal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TOTAL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12), new java.awt.Color(0, 255, 51))); // NOI18N
        JPdetallesBoletas.add(TXTtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 260, 50));

        TXTtipo_moneda.setEditable(false);
        TXTtipo_moneda.setBackground(new java.awt.Color(18, 22, 31));
        TXTtipo_moneda.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        TXTtipo_moneda.setForeground(new java.awt.Color(255, 255, 255));
        TXTtipo_moneda.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TIPO_MONEDA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        JPdetallesBoletas.add(TXTtipo_moneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 260, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(JPdetallesBoletas, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 592, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(JPdetallesBoletas, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_detallesBoletas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_detallesBoletas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_detallesBoletas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_detallesBoletas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_detallesBoletas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPdetallesBoletas;
    public javax.swing.JTable TBLdetallesBoleta;
    public javax.swing.JTextField TXTcodUsuario;
    public javax.swing.JTextField TXTcod_Cliente;
    public javax.swing.JTextField TXTestado;
    public javax.swing.JTextField TXTfecha;
    public javax.swing.JTextField TXTnBoleta;
    public javax.swing.JTextField TXTtipo_moneda;
    public javax.swing.JTextField TXTtipo_pago;
    public javax.swing.JTextField TXTtotal;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
